export const weatherCodeMap = {
    0: { descricao: "Céu limpo", urlDia: "../assets/icons/clear-day.svg", urlNoite: "../assets/icons/clear-night.svg"},
    1: { descricao: "Poucas nuvens", urlDia: "../assets/icons/partly-cloudy-day.svg", urlNoite: "assets/icons/partly-cloudy-night.svg" },
    2: { descricao: "Parcialmente nublado", urlDia: "../assets/icons/cloudy.svg", urlNoite: "assets/icons/cloudy.svg" },
    3: { descricao: "Nublado", urlDia: "../assets/icons/cloudy.svg", urlNoite: "../assets/icons/cloudy.svg" },
    45: { descricao: "Nevoeiro", urlDia: "../assets/icons/fog.svg", urlNoite: "../assets/icons/fog.svg" },
    48: { descricao: "Nevoeiro com geada", urlDia: "../assets/icons/sleet.svg", urlNoite: "../assets/icons/sleet.svg" },
    51: { descricao: "Garoa leve", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    53: { descricao: "Garoa moderada", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    55: { descricao: "Garoa intensa", urlDia: "../assets/icons/heavy-showers.svg", urlNoite: "../assets/icons/heavy-showers.svg" },
    61: { descricao: "Chuva fraca", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    63: { descricao: "Chuva moderada", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    65: { descricao: "Chuva forte", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    66: { descricao: "Nevasca leve", urlDia: "../assets/icons/snow.svg", urlNoite: "../assets/icons/snow.svg" }, 
    67: { descricao: "Nevasca leve", urlDia: "../assets/icons/snow.svg", urlNoite: "../assets/icons/snow.svg" },
    71: { descricao: "Nevasca leve", urlDia: "../assets/icons/thunderstorm-snow.svg", urlNoite: "../assets/icons/thunderstorm-snow.svg"},
    73: { descricao: "Nevasca moderada", urlDia: "../assets/icons/snow.svg", urlNoite: "../assets/icons/snow.svg"},
    75: { descricao: "Nevasca intensa", urlDia: "../assets/icons/heavy-snow.svg", urlNoite: "../assets/icons/heavy-snow.svg"},
    77: { descricao: "Chuva com granizo", urlDia: "../assets/icons/sleet.svg", urlNoite: "../assets/icons/sleet.svg"},
    80: { descricao: "Pancadas de chuva fraca", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    81: { descricao: "Pancadas de chuva moderada", urlDia: "../assets/icons/showers.svg", urlNoite: "../assets/icons/showers.svg" },
    82: { descricao: "Pancadas de chuva forte", urlDia: "../assets/icons/heavy-showers.svg", urlNoite: "../assets/icons/heavy-showers.svg" },
    85: { descricao: "Nevasca", urlDia: "../assets/icons/snow.svg", urlNoite: "../assets/icons/snow.svg" },
    86: { descricao: "Nevasca", urlDia: "../assets/icons/heavy-showers.svg", urlNoite: "../assets/icons/heavy-showers.svg" },
    95: { descricao: "Tempestade", urlDia: "../assets/icons/thunderstorm-showers.svg", urlNoite: "../assets/icons/thunderstorm-showers.svg" },
    96: { descricao: "Tempestade com granizo pequeno", urlDia: "../assets/icons/sleet.svg", urlNoite: "../assets/icons/sleet.svg"  },
    99: { descricao: "Tempestade com granizo grande", urlDia: "../assets/icons/heavy-sleet.svg", urlNoite: "../assets/icons/heavy-sleet.svg"  }
};
