services:
  db:
    image: "docker.io/postgres:17.2"
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  backend:
    build: 
     context: ./Backend/seal-co/
     dockerfile: Dockerfile
    container_name: seal-co-backend
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/{DATABASE_NAME}?schema=public
    volumes:
      - ./Backend/seal-co/src:/usr/src/app/src
    ports:
    - 3000:3000
    depends_on:
      - db
    command: bash -c 'npx prisma migrate reset --force --skip-seed && npx prisma generate && npx prisma migrate dev --name init --skip-seed && npx prisma db seed && npm run start:dev'
  
  frontend:
    build:
     context: ./Frontend
     dockerfile: Dockerfile
    container_name: seal-co-frontend
    volumes:
      - /user/src/frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
volumes:
  pgdata: